version: '3.5'

services:

  squid:
    build:
      context: ./
    ports:
      - "${SQUID_PORT:-3128}:3128"
    volumes:
      - ./cache:/var/cache/squid
      - ./conf/users:/etc/squid/users
    restart: always
